# Generated by Django 4.2.15 on 2024-08-25 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pv_app', '0002_pvlocation_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inverter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the inverter.', max_length=255)),
                ('efficiency', models.DecimalField(decimal_places=2, help_text='Efficiency of the inverter in percentage.', max_digits=5)),
                ('max_power', models.DecimalField(decimal_places=2, help_text='Maximum power rating of the inverter in watts.', max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='PVSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the PV system.', max_length=255)),
                ('area', models.DecimalField(decimal_places=2, help_text='Area of the PV system in square meters.', max_digits=6)),
                ('cells_in_series', models.IntegerField(help_text='Number of cells in series.')),
                ('alpha_sc', models.DecimalField(decimal_places=4, help_text='Temperature coefficient of current (alpha_sc).', max_digits=5)),
                ('gamma_r', models.DecimalField(decimal_places=4, help_text='Gamma_r value for the system.', max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='pvsimulation',
            name='ambient_temperature',
        ),
        migrations.AlterField(
            model_name='pvsimulation',
            name='end_time',
            field=models.DateTimeField(help_text='End time of the simulation in your local time.'),
        ),
        migrations.AlterField(
            model_name='pvsimulation',
            name='location',
            field=models.ForeignKey(help_text='The location of the PV system.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pv_app.pvlocation'),
        ),
        migrations.AlterField(
            model_name='pvsimulation',
            name='module',
            field=models.ForeignKey(help_text='The PV module used in the simulation.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pv_app.pvmodule'),
        ),
        migrations.AlterField(
            model_name='pvsimulation',
            name='start_time',
            field=models.DateTimeField(help_text='Start time of the simulation in your local time.'),
        ),
        migrations.AddField(
            model_name='pvsimulation',
            name='inverter',
            field=models.ForeignKey(help_text='The inverter used in the simulation.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pv_app.inverter'),
        ),
        migrations.AddField(
            model_name='pvsimulation',
            name='pv_system',
            field=models.ForeignKey(help_text='The PV system used in the simulation.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pv_app.pvsystem'),
        ),
    ]
