# Generated by Django 4.2.15 on 2024-08-26 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pv_app', '0003_inverter_pvsystem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pvlocation',
            options={'ordering': ('address',)},
        ),
        migrations.AddField(
            model_name='pvsystem',
            name='pdc0',
            field=models.DecimalField(decimal_places=2, default=1000.0, help_text='Rated DC power output (pdc0) of the PV system in watts.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pvlocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=12, help_text='Latitude of the location in decimal degrees (e.g., 40.7128 for New York).', max_digits=15),
        ),
        migrations.AlterField(
            model_name='pvlocation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=12, help_text='Longitude of the location in decimal degrees (e.g., -74.0060 for New York).', max_digits=15),
        ),
        migrations.AlterField(
            model_name='pvmodule',
            name='i_o_ref',
            field=models.DecimalField(decimal_places=12, help_text='Saturation current at reference conditions (I_o_ref) in amperes.', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='pvsimulation',
            name='inverter',
            field=models.ForeignKey(blank=True, help_text='The inverter used in the simulation.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pv_app.inverter'),
        ),
        migrations.AlterField(
            model_name='pvsystem',
            name='alpha_sc',
            field=models.DecimalField(decimal_places=4, default=0.0001, help_text='Temperature coefficient of current (alpha_sc).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='pvsystem',
            name='area',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Area of the PV system in square meters.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='pvsystem',
            name='cells_in_series',
            field=models.IntegerField(default=1, help_text='Number of cells in series.'),
        ),
        migrations.AlterField(
            model_name='pvsystem',
            name='gamma_r',
            field=models.DecimalField(decimal_places=4, default=0.0001, help_text='Gamma_r value for the system.', max_digits=5),
        ),
    ]
