# Generated by Django 4.2.15 on 2024-08-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pv_app', '0005_pvsystem_gamma_pdc'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvsystem',
            name='modules_per_string',
            field=models.IntegerField(default=1, help_text='Number of modules per string'),
        ),
        migrations.AddField(
            model_name='pvsystem',
            name='strings_per_inverter',
            field=models.IntegerField(default=1, help_text='Number of strings per inverter'),
        ),
    ]
