# Generated by Django 4.2.15 on 2024-08-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pv_app', '0006_pvsystem_modules_per_string_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvmodule',
            name='efficiency',
            field=models.FloatField(help_text='The efficiency of the PV module.', null=True),
        ),
        migrations.AddField(
            model_name='pvmodule',
            name='module_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
