# Generated by Django 4.2.15 on 2024-08-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pv_app', '0008_remove_pvsimulation_pv_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvsimulation',
            name='modules_per_string',
            field=models.IntegerField(default=10),
        ),
    ]
